name: DeepBind
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=2.0.5
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blas=1.0
  - bottleneck=1.3.2
  - brotli=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2022.2.1
  - certifi=2021.10.8
  - cudatoolkit=11.3.1
  - cycler=0.11.0
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.1
  - entrypoints=0.4
  - et_xmlfile=1.1.0
  - executing=0.8.3
  - expat=2.4.4
  - ffmpeg=4.3
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.11.0
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - intel-openmp=2021.4.0
  - ipykernel=6.9.1
  - ipython=8.1.1
  - jedi=0.18.1
  - joblib=1.1.0
  - jpeg=9d
  - jupyter_client=7.1.2
  - jupyter_core=4.9.2
  - kiwisolver=1.3.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=9.3.0
  - libiconv=1.15
  - libidn2=2.3.2
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuuid=1.0.3
  - libuv=1.40.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.14
  - libxml2=2.9.12
  - lz4-c=1.9.3
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - ncurses=6.3
  - nest-asyncio=1.5.4
  - nettle=3.7.3
  - numexpr=2.8.1
  - numpy=1.21.2
  - numpy-base=1.21.2
  - openh264=2.1.1
  - openpyxl=3.0.9
  - openssl=1.1.1n
  - packaging=21.3
  - pandas=1.4.1
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.0.1
  - pip=21.2.4
  - prompt-toolkit=3.0.27
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.11.2
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - python=3.8.12
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytorch=1.10.2
  - pytorch-mutex=1.0
  - pytz=2021.3
  - pyzmq=19.0.2
  - qt=5.9.7
  - readline=8.1.2
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - setuptools=58.0.4
  - sip=4.19.13
  - six=1.16.0
  - sqlite=3.37.2
  - stack_data=0.2.0
  - threadpoolctl=2.2.0
  - tk=8.6.11
  - torchaudio=0.10.2
  - torchvision=0.11.3
  - tornado=6.1
  - traitlets=5.1.1
  - typing_extensions=3.10.0.2
  - wcwidth=0.2.5
  - wheel=0.37.1
  - xz=5.2.5
  - zeromq=4.3.4
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - logomaker==0.8
prefix: /home/djinb1127/miniconda3/envs/DeepBind
